name: crisp
description: Continuous relaxation in structured pruning
dockerbuild:
- name: crisptrain
  dockerfile: dockerfile-train
  context: .
- name: crispdev
  dockerfile: dockerfile
  context: .
  build_arg:
  - key: IMAGE
    value: crisptrain
  - key: SUDOUSER
    value: ai
version:
  major: 0
  minor: 1
  patch: 0
  label: ''
gpus: all
image_names:
- name: crisptrain
  image_name: localhost:32000/crisptrain:0.1.0
- name: crispdev
  image_name: localhost:32000/crispdev:0.1.0
